"""書類生成サービス - ReportLab使用"""
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from app.config import settings

def _register_fonts():
    for fp in ["/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc", "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"]:
        if os.path.exists(fp):
            try:
                pdfmetrics.registerFont(TTFont("JaFont", fp))
                return "JaFont"
            except: continue
    return "Helvetica"

FONT_NAME = _register_fonts()
HEADER_COLOR = colors.HexColor("#1F3864")
ALT_ROW = colors.HexColor("#EEF3FA")
BORDER = colors.HexColor("#CCCCCC")

def _s(name, **kw):
    return ParagraphStyle(name, fontName=FONT_NAME, **kw)

def _fmt(val, currency="JPY"):
    try:
        v = float(str(val).replace(",",""))
        if currency == "JPY": return f"¥{v:,.0f}"
        elif currency == "USD": return f"${v:,.2f}"
        return f"{v:,.2f} {currency}"
    except: return str(val)

def _items_table(items, currency="JPY"):
    styles = {"h": _s("h", fontSize=9, textColor=colors.white, alignment=TA_CENTER), "c": _s("c", fontSize=9), "cr": _s("cr", fontSize=9, alignment=TA_RIGHT)}
    header = [Paragraph(t, styles["h"]) for t in ["品名/Product Name","SKU","数量","単位","単価","金額"]]
    rows = [header]
    for i, item in enumerate(items):
        rows.append([Paragraph(str(item.get("product_name","")), styles["c"]), Paragraph(str(item.get("sku","")), styles["c"]), Paragraph(str(item.get("quantity","")), styles["cr"]), Paragraph(str(item.get("unit","個")), styles["c"]), Paragraph(_fmt(item.get("unit_price",0), currency), styles["cr"]), Paragraph(_fmt(item.get("amount",0), currency), styles["cr"])])
    t = Table(rows, colWidths=[60*mm,25*mm,18*mm,15*mm,30*mm,30*mm], repeatRows=1)
    t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),HEADER_COLOR),("FONTNAME",(0,0),(-1,-1),FONT_NAME),("FONTSIZE",(0,0),(-1,-1),9),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5),("GRID",(0,0),(-1,-1),0.5,BORDER),("ROWBACKGROUNDS",(0,1),(-1,-1),[ALT_ROW,colors.white])]))
    return t

def generate_po_pdf(data, output_path):
    currency = data.get("currency","JPY")
    doc = SimpleDocTemplate(output_path, pagesize=A4, leftMargin=20*mm, rightMargin=20*mm, topMargin=20*mm, bottomMargin=20*mm)
    title_s = _s("title", fontSize=20, alignment=TA_CENTER, textColor=HEADER_COLOR)
    sub_s = _s("sub", fontSize=10, alignment=TA_CENTER, textColor=colors.HexColor("#555555"))
    normal_s = _s("normal", fontSize=9)
    total_s = _s("total", fontSize=11, textColor=HEADER_COLOR, alignment=TA_RIGHT)
    footer_s = _s("footer", fontSize=8, textColor=colors.HexColor("#aaaaaa"), alignment=TA_CENTER)
    story = [Paragraph("PURCHASE ORDER", title_s), Paragraph("発注書", sub_s), HRFlowable(width="100%", thickness=2, color=HEADER_COLOR, spaceAfter=8)]
    items = data.get("items",[]) or [{"product_name":"（明細なし）","sku":"","quantity":0,"unit":"個","unit_price":0,"amount":0}]
    story.append(Paragraph(f"P.O. No: {data.get('po_number','')}  |  Date: {data.get('order_date','')}  |  Supplier: {data.get('supplier','')}  |  Currency: {currency}", normal_s))
    story.append(Spacer(1,4*mm))
    story.append(_items_table(items, currency))
    story.append(Spacer(1,4*mm))
    total = data.get("total_amount", sum(float(str(i.get("amount",0)).replace(",","")) for i in items))
    story.append(Paragraph(f"合計金額 / Total: {_fmt(total, currency)}", total_s))
    story.append(Spacer(1,8*mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Paragraph(f"Generated by 貿易業務自動化システム | {datetime.now().strftime('%Y-%m-%d %H:%M')}", footer_s))
    doc.build(story)
    return output_path

def generate_invoice_pdf(data, output_path):
    currency = data.get("currency","JPY")
    doc = SimpleDocTemplate(output_path, pagesize=A4, leftMargin=20*mm, rightMargin=20*mm, topMargin=20*mm, bottomMargin=20*mm)
    title_s = _s("title", fontSize=20, alignment=TA_CENTER, textColor=HEADER_COLOR)
    sub_s = _s("sub", fontSize=10, alignment=TA_CENTER, textColor=colors.HexColor("#555555"))
    normal_s = _s("normal", fontSize=9)
    total_s = _s("total", fontSize=11, textColor=HEADER_COLOR, alignment=TA_RIGHT)
    footer_s = _s("footer", fontSize=8, textColor=colors.HexColor("#aaaaaa"), alignment=TA_CENTER)
    story = [Paragraph("COMMERCIAL INVOICE", title_s), Paragraph("商業請求書", sub_s), HRFlowable(width="100%", thickness=2, color=HEADER_COLOR, spaceAfter=8)]
    items = data.get("items",[]) or [{"product_name":"（明細なし）","sku":"","quantity":0,"unit":"個","unit_price":0,"amount":0}]
    story.append(Paragraph(f"Invoice No: {data.get('invoice_number','')}  |  Date: {data.get('invoice_date','')}  |  Bill To: {data.get('customer','')}  |  Currency: {currency}", normal_s))
    story.append(Spacer(1,4*mm))
    story.append(_items_table(items, currency))
    story.append(Spacer(1,4*mm))
    subtotal = sum(float(str(i.get("amount",0)).replace(",","")) for i in items)
    tax = float(str(data.get("tax_amount",0)).replace(",",""))
    total = float(str(data.get("total_amount", subtotal+tax)).replace(",",""))
    story.append(Paragraph(f"小計: {_fmt(subtotal, currency)}  |  税: {_fmt(tax, currency)}  |  合計: {_fmt(total, currency)}", total_s))
    story.append(Spacer(1,8*mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Paragraph(f"Generated by 貿易業務自動化システム | {datetime.now().strftime('%Y-%m-%d %H:%M')}", footer_s))
    doc.build(story)
    return output_path

def generate_packing_list_pdf(data, output_path):
    return generate_po_pdf({**data, "po_number": data.get("pl_number",""), "supplier": data.get("shipper",""), "order_date": data.get("ship_date","")}, output_path)

def generate_document(doc_type, data, filename):
    output_path = str(settings.GENERATED_DIR / filename)
    generators = {"po": generate_po_pdf, "invoice": generate_invoice_pdf, "packing_list": generate_packing_list_pdf}
    return generators.get(doc_type, generate_po_pdf)(data, output_path)
